<a href="https://colab.research.google.com/github/deepanshuchoudhary448/45-day-of-python/blob/main/day14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **sorting**

1. df.sort_values("column_name") -> Sort by Single Column
2. df.sort_values("Age", ascending=True) -> Sort in Ascending Order
3. df.sort_values("Age", ascending=False) -> Sort in Descending Order
4. df.sort_values(["col1", "col2"]) -> Sort Multiple Columns
5. df.sort_values( ["Age", "Salary"], ascending=[True, False] ) -> Multiple Columns with Descending Order

In [21]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
# df.sort_values("english") for ascending
df.sort_values("name",ascending=False) #desceding

# by deafult asceding method 1
# df.sort_values(by=['english'],ascending=[False])

#multiple cols sort
# df.sort_values(by=['english','maths'],ascending= [False,'True'])
# a to z
df ['name'] = df['name'].str.lower()
df.sort_values('name')

       name  gender  physics  maths  english
0      arun    Male       88     87       78
8    dinesh    Male       56     45       67
10    gowri  Female      100    100      100
9      hema  Female       71     90       23
13  jenifer  Female       67     88       90
7   kavitha  Female       78     71       67
2   moorthy    Male       89     90       70
12  murugan    Male       34     89       78
5     priya  Female       56     46       78
3      raja    Male       30     25       40
1    rajesh    Male       96    100       95
11      ram    Male       78     55       47
6    sundar    Male       12     67       67
4      usha  Female       67     45       78

In [27]:
df
# add column
df['total '] = df['english'] + df['maths'] + df['english']
df
# add row
df.loc[14] = ["total", 'male',30,45,56,234]
df
#update column

#update row

# delete column
df.drop("total",axis=1)
df
#delete row
df.drop(14,axis=0)
#

KeyError: "['total'] not found in axis"

Working with date value
1. df['doj'] -> Add New Date Column
2. df['doj'].dtype -> Check Data Type of Date Column
3. df['doj'] = pd.to_datetime(df['doj']) -> Convert Object to Datetime
4. df['doj'].dtype -> Check Data Type of Date Column
5. pd.Timestamp.now() -> Get Current Date & Time
6. df['doj'].dt.year -> Extract Year
7.df['doj'].dt.month -> Extract Month
8. df['doj'].dt.day -> Extract Day
9. df[(df['doj'] >= '2024-01-01') & (df['doj'] <= '2024-12-31')] -> Filter Between Two Dates

In [32]:
df
# df.drop([6,7,8,9,10,11,12,13,14],inplace = True)
df
df['doj'] = ['2025-01-01','2025-02-02','2025-03-03','2025-04-04','2025-05-05','2025-06-06']
df

      name  gender  physics  maths  english  total          doj
0     arun    Male       88     87       78     243  2025-01-01
1   rajesh    Male       96    100       95     290  2025-02-02
2  moorthy    Male       89     90       70     230  2025-03-03
3     raja    Male       30     25       40     105  2025-04-04
4     usha  Female       67     45       78     201  2025-05-05
5    priya  Female       56     46       78     202  2025-06-06

In [38]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)

df['doj'] = ['2025-01-01','2025-02-02','2025-03-03','2025-04-04','2025-05-05']
df['doj'].dtype
# convert string to date
df['doj'] =pd.to_datetime(df['doj'])
df['doj'].dtype
# date operation
df['doj'].dt.year
df['doj'].dt.month
df['doj'].dt.day
df['doj'].dt.day_name()
df

#20 days
df['doj'] + pd.to_timedelta("20 days")
df

       name  roll no  marks        doj
0   dheeraj      123     10 2025-01-01
1     kunal     1234     20 2025-02-02
2  abhishek    12345     30 2025-03-03
3   praveen    12356     40 2025-04-04
4    anjali  1234567     50 2025-05-05